<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>exe</OutputType>
    <NoWarn>$(NoWarn);MAAIW001</NoWarn>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\AutonomousPhasePipelineApp.Core\AutonomousPhasePipelineApp.Core.csproj" />
    <ProjectReference Include="..\..\..\NexusLabs.Foundry.MicrosoftAgentFramework.Workflows\NexusLabs.Foundry.MicrosoftAgentFramework.Workflows.csproj" />
  </ItemGroup>

</Project>
