namespace NexusLabs.Foundry.MicrosoftAgentFramework.Harness;

internal enum HarnessProviderCompositionStatus
{
    Success,
    ExecutionBindingInvalid,
    CompositionGuardRejected,
    GeneratedToolResolutionFailed,
    GeneratedToolsEmpty,
    GeneratedToolsNotEnabled,
    FunctionInvocationLoopMissing,
    MessageInjectionMissing,
    HistoryProviderRequired,
    HistoryProviderUnexpected,
    HistoryProviderModeMismatch,
    HistoryProviderUnsupportedPersistenceMode,
    PlanningPluginUnexpected,
    TodoProviderRequired,
    TodoProviderUnexpected,
    AgentModeProviderRequired,
    AgentModeProviderUnexpected,
    ProviderStateKeyCollision,
    FoundryMetricsMissing,
    ApprovalPluginUnexpected,
    ApprovalResponseBindingRequired,
    ApprovalResponseBindingUnexpected,
    ApprovalNotRequiredBypassingRequired,
    ApprovalNotRequiredBypassingUnexpected,
    ToolAutoApprovalRequired,
    ToolAutoApprovalUnexpected,
    SkillsPluginUnexpected,
    SkillsPluginRequired,
    SkillsApprovalCoherenceRequired,
    WebSearchPluginUnexpected,
    WebSearchPluginRequired,
    WebSearchToolNameCollision,
    WebSearchToolTypeCollision,
}
