<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <IsPackable>false</IsPackable>
    <NoWarn>$(NoWarn);MAAI001</NoWarn>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\NexusLabs.Foundry.MicrosoftAgentFramework\NexusLabs.Foundry.MicrosoftAgentFramework.csproj" />
    <ProjectReference Include="..\NexusLabs.Foundry.MicrosoftAgentFramework.Harness\NexusLabs.Foundry.MicrosoftAgentFramework.Harness.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Using Include="Xunit" />
  </ItemGroup>

</Project>
